// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parametriz.AutoNFP.Data.Context;

#nullable disable

namespace Parametriz.AutoNFP.Data.Migrations
{
    [DbContext(typeof(AutoNfpDbContext))]
    [Migration("20251019202437_UsuariosFotoUpload")]
    partial class UsuariosFotoUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.CuponsFiscais.CupomFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CadastradoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InstituicaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CadastradoPorId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("CuponsFiscais", (string)null);
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes", (string)null);
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Administrador")
                        .HasColumnType("boolean");

                    b.Property<bool>("Desativado")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoUpload")
                        .HasColumnType("text");

                    b.Property<Guid>("InstituicaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId", "Nome")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Voluntarios.Voluntario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Emissor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntidadeNomeNFP")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("InstituicaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Requerente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("Senha")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Upload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ValidoAPartirDe")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId")
                        .IsUnique();

                    b.ToTable("Voluntarios", (string)null);
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.CuponsFiscais.CupomFiscal", b =>
                {
                    b.HasOne("Parametriz.AutoNFP.Domain.Usuarios.Usuario", "CadastradoPor")
                        .WithMany("CuponsFiscais")
                        .HasForeignKey("CadastradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", "Instituicao")
                        .WithMany("CuponsFiscais")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.ChaveDeAcesso", "ChaveDeAcesso", b1 =>
                        {
                            b1.Property<Guid>("CupomFiscalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Chave")
                                .IsRequired()
                                .HasMaxLength(44)
                                .HasColumnType("character(44)")
                                .HasColumnName("Chave")
                                .IsFixedLength();

                            b1.Property<DateTime?>("Competencia")
                                .IsRequired()
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("Competencia");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("Numero");

                            b1.HasKey("CupomFiscalId");

                            b1.HasIndex("Chave")
                                .IsUnique();

                            b1.ToTable("CuponsFiscais");

                            b1.WithOwner()
                                .HasForeignKey("CupomFiscalId");

                            b1.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.CnpjCpf", "Cnpj", b2 =>
                                {
                                    b2.Property<Guid>("ChaveDeAcessoCupomFiscalId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("NumeroInscricao")
                                        .IsRequired()
                                        .HasMaxLength(14)
                                        .HasColumnType("character(14)")
                                        .HasColumnName("Cnpj")
                                        .IsFixedLength();

                                    b2.HasKey("ChaveDeAcessoCupomFiscalId");

                                    b2.ToTable("CuponsFiscais");

                                    b2.WithOwner()
                                        .HasForeignKey("ChaveDeAcessoCupomFiscalId");
                                });

                            b1.Navigation("Cnpj");
                        });

                    b.Navigation("CadastradoPor");

                    b.Navigation("ChaveDeAcesso");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", b =>
                {
                    b.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("InstituicaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .HasMaxLength(8)
                                .HasColumnType("character(8)")
                                .HasColumnName("CEP")
                                .IsFixedLength();

                            b1.Property<string>("Complemento")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Municipio");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Numero");

                            b1.Property<string>("TipoLogradouro")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("TipoLogradouro");

                            b1.Property<string>("UF")
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("UF")
                                .IsFixedLength();

                            b1.HasKey("InstituicaoId");

                            b1.ToTable("Instituicoes");

                            b1.WithOwner()
                                .HasForeignKey("InstituicaoId");
                        });

                    b.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.CnpjCpf", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("InstituicaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NumeroInscricao")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("CnpjCpf");

                            b1.Property<int>("TipoPessoa")
                                .HasMaxLength(1)
                                .HasColumnType("integer")
                                .HasColumnName("TipoPessoa")
                                .IsFixedLength();

                            b1.HasKey("InstituicaoId");

                            b1.HasIndex("NumeroInscricao")
                                .IsUnique();

                            b1.ToTable("Instituicoes");

                            b1.WithOwner()
                                .HasForeignKey("InstituicaoId");
                        });

                    b.Navigation("Cnpj");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", "Instituicao")
                        .WithMany("Usuarios")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Conta")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Conta")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Voluntarios.Voluntario", b =>
                {
                    b.HasOne("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", "Instituicao")
                        .WithOne("Voluntario")
                        .HasForeignKey("Parametriz.AutoNFP.Domain.Voluntarios.Voluntario", "InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Parametriz.AutoNFP.Core.ValueObjects.CnpjCpf", "CnpjCpf", b1 =>
                        {
                            b1.Property<Guid>("VoluntarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NumeroInscricao")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("CnpjCpf");

                            b1.Property<int>("TipoPessoa")
                                .HasMaxLength(1)
                                .HasColumnType("integer")
                                .HasColumnName("TipoPessoa")
                                .IsFixedLength();

                            b1.HasKey("VoluntarioId");

                            b1.ToTable("Voluntarios");

                            b1.WithOwner()
                                .HasForeignKey("VoluntarioId");
                        });

                    b.Navigation("CnpjCpf");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Instituicoes.Instituicao", b =>
                {
                    b.Navigation("CuponsFiscais");

                    b.Navigation("Usuarios");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("Parametriz.AutoNFP.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("CuponsFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
